#ifndef MACRO_H
#define MACRO_H

// Response Messages

#define RPL_WELCOME "001"
#define RPL_WELCOME_MSG "Welcome to the server"
#define RPL_TOPIC "332"
#define RPL_TOPIC_MSG "Topic of the channel"
#define RPL_NAMREPLY "353"
#define RPL_NAMREPLY_MSG "Reply name"
#define RPL_INVITING "341"
#define RPL_INVITING_MSG "Inviting you to join"

// Error Messages

#define ERR_NEEDMOREPARAMS "461"
#define ERR_NEEDMOREPARAMS_MSG "Not enough parameters"
#define ERR_ALREADYREGISTERED "462"
#define ERR_ALREADYREGISTERED_MSG "You are already registered"
#define ERR_PASSWDMISMATCH "464"
#define ERR_PASSWDMISMATCH_MSG "Password mismatch"
#define ERR_NONICKNAMEGIVEN "431"
#define ERR_NONICKNAMEGIVEN_MSG "No nickname given"
#define ERR_ERRONEUSNICKNAME "432"
#define ERR_ERRONEUSNICKNAME_MSG "Erroneous nickname"
#define ERR_NICKNAMEINUSE "433"
#define ERR_NICKNAMEINUSE_MSG "Nickname in use"
#define ERR_NICKCOLLISION "436"
#define ERR_NICKCOLLISION_MSG "Nickname collision"
#define ERR_NOORIGIN "409"
#define ERR_NOORIGIN_MSG "No origin specified"
#define ERR_NOSUCHNICK "401"
#define ERR_NOSUCHNICK_MSG "No such nickname"
#define ERR_NOSUCHCHANNEL "403"
#define ERR_NOSUCHCHANNEL_MSG "No such channel"
#define ERR_CANNOTSENDTOCHAN "404"
#define ERR_CANNOTSENDTOCHAN_MSG "Cannot send to channel"
#define ERR_NOTEXTTOSEND "412"
#define ERR_NOTEXTTOSEND_MSG "No text to send"
#define ERR_NOTONCHANNEL "442"
#define ERR_NOTONCHANNEL_MSG "Not on channel"
#define ERR_CHANOPRIVSNEEDED "482"
#define ERR_CHANOPRIVSNEEDED_MSG "Channel operator privileges needed"
#define ERR_USERNOTINCHANNEL "441"
#define ERR_USERNOTINCHANNEL_MSG "User not in channel"
#define ERR_USERONCHANNEL "443"
#define ERR_USERONCHANNEL_MSG "User already on channel"
#define ERR_BADCHANNELKEY "475"
#define ERR_BADCHANNELKEY_MSG "Bad channel key"
#define ERR_INVITEONLYCHAN "473"
#define ERR_INVITEONLYCHAN_MSG "Invite only channel"
#define ERR_CHANNELISFULL "471"
#define ERR_CHANNELISFULL_MSG "Channel is full"
#define ERR_NOTREGISTERED "451"
#define ERR_NOTREGISTERED_MSG "Not registered"
#define ERR_ERRONEUSNICKNAME "432"
#define ERR_ERRONEUSNICKNAME_MSG "Erroneous nickname"
#define ERR_NORECIPIENT "411"
#define ERR_NORECIPIENT_MSG "No recipient"

#endif // MACRO_H
